version: '3'

services:
    database:
        image: mysql
        container_name: stock-db
        ports:
            - 53306:3306
        volumes:
            - ./docker/data:/home/mysql/data
        environment:
            MYSQL_ROOT_PASSWORD: pwd
        command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
        networks:
            - default
            - my_stock_app_net

networks:
    my_stock_app_net:
        driver: bridge
