---
spring:
    config:
        activate:
            on-profile: default
    datasource:
        batch:
            username: root
            password: pwd
            driver-class-name: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://localhost:53306/batch
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
---
spring:
    config:
        activate:
            on-profile: test
    datasource:
        batch:
            username: sa
            password:
            driver-class-name: org.h2.Driver
            jdbc-url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
---
spring:
    config:
        activate:
            on-profile: local
    datasource:
        batch:
            username: root
            password: pwd
            driver-class-name: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://localhost:53306/batch
        stock:
            username: root
            password: pwd
            pool-name: Local-Stock-HikariPool
            jdbc-url: jdbc:mysql://localhost:53306/stock
            driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true

slack:
    token: ENC(U6Ej7PluvvslzvvJ7vaMnBdw/81WJ/rYvdLBl+rMfFTATCR5pNS9/0u8JG/Ep3vFTqa2U1c7IVwsteRmBNEZzzRJWXOg+Vur)

---
spring:
    config:
        activate:
            on-profile: prod
    datasource:
        batch:
            username: root
            password: gkswkdgh
            driver-class-name: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://mysql.db.svc.cluster.local:3306/batch
        stock:
            username: root
            password: gkswkdgh
            driver-class-name: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://mysql.db.svc.cluster.local:3306/stock

slack:
    token: ENC(U6Ej7PluvvslzvvJ7vaMnBdw/81WJ/rYvdLBl+rMfFTATCR5pNS9/0u8JG/Ep3vFTqa2U1c7IVwsteRmBNEZzzRJWXOg+Vur)
