# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: STOCK BATCH

on:
    push:
        branches: [ master, feature/setting-github-action ]
    pull_request:
        branches: [ develop, master ]
        paths:
            - stock-batch/**

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   name: Set up JDK 11
                uses: actions/setup-java@v2
                with:
                    java-version: '11'
                    distribution: 'temurin'
            -   name: Build with Gradle
                uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
                with:
                    arguments: clean stock-batch:build
            -   name: cache source code
                uses: actions/cache@v2
                env:
                    cache-name: cache-source-code
                with:
                    path: ./**
                    key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.run_number }}
                    restore-keys: |
                        ${{ runner.os }}-build-${{ env.cache-name }}
                        ${{ runner.os }}-build-
                        ${{ runner.os }}-
    deploy:
        #        if: ${{ github.ref == 'refs/heads/master' }}
        needs: build
        runs-on: ubuntu-latest
        steps:
            # aws credentials
            -   name: Configure AWS credentials
                uses: aws-actions/configure-aws-credentials@v1
                with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: ${{ secrets.AWS_SERVICE_REGION }}

            -   name: Login to Amazon ECR
                id: login-ecr
                uses: aws-actions/amazon-ecr-login@v1

            # Build Docker Image
            -   name: Build Docker Image
                run: |
                    cd ../../
                    tree
                    docker build --build-arg JAR_FILE=./stock-batch/build/libs/stock-batch-0.0.1-SNAPSHOT.jar -t stock/batch:${{github.run_number}} .
                    docker tag stock/batch:${{github.run_number}} 702867482623.dkr.ecr.ap-northeast-2.amazonaws.com/stock/batch:${{github.run_number}}
            # Push Docker Image
            -   name: Push Docker Image
                run: |
                    docker push 702867482623.dkr.ecr.ap-northeast-2.amazonaws.com/stock/batch:${{github.run_number}}
